site_name: Test Site

theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.follow

  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
    - toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
    - toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        
  features:
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.follow


plugins:
  - search

extra_css:
  - assets/css/extra.css
  - assets/css/landing.css


nav:
    - Home: index.md
    - Resume: resume.md
    - Portfolio:
      - Overview: portfolio/firmwarecheck/index.md
      - Overview: portfolio/firmwarecheck/index.md
      - Documentation Approach: portfolio/firmwarecheck/documentation-approach.md
      - Getting Started: portfolio/firmwarecheck/getting-started.md
      
      
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg